name: NOAH frontend production

on:
  push:
    branches: [ "main" ]

jobs:

  docker-build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3.10.0
      id: buildx

    - name: Cache Docker image layers
      uses: actions/cache@v4.2.3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-key: |
          ${{ runner.os }}-buildx-
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      id: docker_build
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/noah_fe_production
        cache-to: type=local,dest=./tmp/.buildx-cache
        cache-from: type=local,src=./tmp/.buildx-cache

    - name: Verify CI/CD pipeline
      run: echo ${{ steps.docker_build.outputs.digest }}
